from selenium import webdriver
import time
driver = webdriver.Firefox(executable_path='C:\Python\geckodriver.exe')
driver.maximize_window()
print("Waiting for home page to open...")
driver.get("http://localhost:3000/")
print("Page opened Successfully!")
time.sleep(1)
driver.find_element_by_xpath("/html/body/div/div[1]/nav/div/ul/li/a").click()
time.sleep(1)
print("Login page is opened")
username = driver.find_element_by_name("user_name")
print("Is Username displayed ? ", username.is_displayed())
print("Is Username enabled ? ", username.is_enabled())
time.sleep(1)
passw = driver.find_element_by_name("password")
print("Is Password displayed ? ", passw.is_displayed())
print("Is Password enabled ? ", passw.is_enabled())
time.sleep(1)
print("Logging in as admin... ")
username.send_keys("admin")
passw.send_keys("admin")
time.sleep(1)
driver.find_element_by_xpath("/html/body/div/div[2]/div/div/div/div/div[1]/div/form/div[3]/div[1]/button").click()
print("Login Successful!")
time.sleep(1)

driver.quit()
